using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// In-game HUD for configuring and triggering deliveries.
///
/// ── Inspector wiring guide ───────────────────────────────────────────────────
///
///  [Weather Selection]
///    weatherDropdown     — TMP_Dropdown — auto-populated from WeatherRosterSO
///    weatherSummaryLabel — TMP_Text     — updated on every weather change;
///                                         generated by CricketDataController.GenerateWeatherSummary()
///
///  [Bowler Selection]
///    bowlerDropdown    — TMP_Dropdown — auto-populated from BowlerRosterSO
///
///  [Speed — always visible]
///    speedSlider       — Slider      — range set automatically from bowler SO
///    speedLabel        — TMP_Text    — e.g. "Speed: 38.0 m/s  (137 km/h)"
///
///  [Swing Group — shown for Fast and Medium bowlers]
///    swingGroup        — GameObject  — parent of swing slider + label;
///                                      shown/hidden by bowler type
///    swingSlider       — Slider      — signed: negative = out-swing, positive = in-swing
///    swingLabel        — TMP_Text    — e.g. "Swing: 1.20 m/s²  (In)"
///
///  [Spin Group — shown for Spin and Medium bowlers]
///    spinGroup         — GameObject  — parent of spin slider + label;
///                                      shown/hidden by bowler type
///    spinSlider        — Slider      — signed: negative = leg-break, positive = off-break
///    spinLabel         — TMP_Text    — e.g. "Spin: 3.50 m/s  (Off)"
///
/// ── Flow ─────────────────────────────────────────────────────────────────────
///   OnEnable  → populate weather dropdown → select index 0
///             → populate bowler dropdown  → select index 0
///   Weather change → model.SetSelectedWeather → UpdateWeatherSummary
///   Bowler  change → model.SetSelectedBowler (auto-sets arm from BowlerConfigSO)
///               → RefreshPanelVisibility (swing/spin groups)
///               → RefreshSliderRanges
///   Sliders → push values to CricketGameModel
///   Space (CricketGameController) → reads model → fires BallThrowData
/// </summary>
public class CricketInGameHUD : MonoBehaviour
{
    [Header("Weather Selection")]
    [Tooltip("Populated automatically from WeatherRosterSO via CricketDataController.")]
    [SerializeField] private TMP_Dropdown weatherDropdown;
    [Tooltip("Displays a plain-English summary of every effect the selected weather applies.\n" +
             "Updated automatically whenever the weather dropdown changes.")]
    [SerializeField] private TMP_Text     weatherSummaryLabel;

    [Header("Bowler Selection")]
    [SerializeField] private TMP_Dropdown bowlerDropdown;

    [Header("Wicket Approach")]
    [Tooltip("Two-option dropdown: 'Over the Wicket' (index 0) and 'Around the Wicket' (index 1).\n" +
             "Selecting either option calls CricketGameModel.SetWicketApproach, which determines\n" +
             "which release point is read from the active BowlerConfigSO on the next delivery.")]
    [SerializeField] private TMP_Dropdown approachDropdown;

    [Header("Speed — all bowlers")]
    [SerializeField] private Slider   speedSlider;
    [SerializeField] private TMP_Text speedLabel;

    [Header("Swing — Fast and Medium bowlers")]
    [Tooltip("Parent GameObject containing the swing slider and label.")]
    [SerializeField] private GameObject swingGroup;
    [SerializeField] private Slider     swingSlider;
    [SerializeField] private TMP_Text   swingLabel;

    [Header("Spin — Spin and Medium bowlers")]
    [Tooltip("Parent GameObject containing the spin slider and label.")]
    [SerializeField] private GameObject spinGroup;
    [SerializeField] private Slider     spinSlider;
    [SerializeField] private TMP_Text   spinLabel;

    private WeatherRosterSO weatherRoster;
    private BowlerRosterSO  roster;
    private BowlerConfigSO        currentBowler;

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    private void OnEnable()
    {
        CricketDataController dataCtrl = CricketGameModel.Instance.GetDataController();

        weatherRoster = dataCtrl.GetWeatherRoster();
        roster        = dataCtrl.GetBowlerRoster();

        PopulateWeatherDropdown();
        PopulateBowlerDropdown();
        PopulateApproachDropdown();
        SubscribeListeners();

        // Initialise with the first weather preset
        if (weatherRoster != null && weatherRoster.weathers.Count > 0)
            OnWeatherSelected(0);

        // Initialise with the first bowler (fires all Refresh* methods)
        if (roster != null && roster.bowlers.Count > 0)
            OnBowlerSelected(0);

        // Default to Over the Wicket
        OnApproachSelected(0);
    }

    private void OnDisable()
    {
        UnsubscribeListeners();
    }

    // ── Dropdown population ───────────────────────────────────────────────────

    private void PopulateWeatherDropdown()
    {
        if (weatherDropdown == null) return;
        if (weatherRoster == null || weatherRoster.weathers.Count == 0)
        {
            Debug.LogWarning("[CricketInGameHUD] WeatherRosterSO is null or empty — " +
                             "run Cricket → Generate Weather Presets, then assign WeatherRoster to CricketDataController.");
            return;
        }

        weatherDropdown.ClearOptions();
        var options = new List<TMP_Dropdown.OptionData>();
        foreach (WeatherConfigSO preset in weatherRoster.weathers)
            options.Add(new TMP_Dropdown.OptionData(preset != null ? preset.weatherName : "(null)"));
        weatherDropdown.AddOptions(options);
    }

    private void PopulateApproachDropdown()
    {
        if (approachDropdown == null) return;

        approachDropdown.ClearOptions();
        approachDropdown.AddOptions(new List<TMP_Dropdown.OptionData>
        {
            new TMP_Dropdown.OptionData("Over the Wicket"),
            new TMP_Dropdown.OptionData("Around the Wicket")
        });
    }

    private void PopulateBowlerDropdown()
    {
        if (bowlerDropdown == null) return;
        if (roster == null)
        {
            Debug.LogWarning("[CricketInGameHUD] BowlerRosterSO is null — " +
                             "assign it to CricketDataController in the Inspector.");
            return;
        }

        bowlerDropdown.ClearOptions();
        var options = new List<TMP_Dropdown.OptionData>();
        foreach (BowlerConfigSO bowler in roster.bowlers)
            options.Add(new TMP_Dropdown.OptionData(bowler.bowlerName));
        bowlerDropdown.AddOptions(options);
    }

    // ── Listener management ───────────────────────────────────────────────────

    private void SubscribeListeners()
    {
        if (weatherDropdown != null)
        {
            weatherDropdown.onValueChanged.RemoveListener(OnWeatherSelected);
            weatherDropdown.onValueChanged.AddListener(OnWeatherSelected);
        }
        if (approachDropdown != null)
        {
            approachDropdown.onValueChanged.RemoveListener(OnApproachSelected);
            approachDropdown.onValueChanged.AddListener(OnApproachSelected);
        }
        if (bowlerDropdown != null)
        {
            bowlerDropdown.onValueChanged.RemoveListener(OnBowlerSelected);
            bowlerDropdown.onValueChanged.AddListener(OnBowlerSelected);
        }
        if (speedSlider != null)
        {
            speedSlider.onValueChanged.RemoveListener(OnSpeedChanged);
            speedSlider.onValueChanged.AddListener(OnSpeedChanged);
        }
        if (swingSlider != null)
        {
            swingSlider.onValueChanged.RemoveListener(OnSwingChanged);
            swingSlider.onValueChanged.AddListener(OnSwingChanged);
        }
        if (spinSlider != null)
        {
            spinSlider.onValueChanged.RemoveListener(OnSpinChanged);
            spinSlider.onValueChanged.AddListener(OnSpinChanged);
        }
    }

    private void UnsubscribeListeners()
    {
        weatherDropdown?.onValueChanged.RemoveListener(OnWeatherSelected);
        approachDropdown?.onValueChanged.RemoveListener(OnApproachSelected);
        bowlerDropdown?.onValueChanged.RemoveListener(OnBowlerSelected);
        speedSlider?.onValueChanged.RemoveListener(OnSpeedChanged);
        swingSlider?.onValueChanged.RemoveListener(OnSwingChanged);
        spinSlider?.onValueChanged.RemoveListener(OnSpinChanged);
    }

    // ── Callbacks ─────────────────────────────────────────────────────────────

    private void OnWeatherSelected(int index)
    {
        if (weatherRoster == null || index < 0 || index >= weatherRoster.weathers.Count) return;
        WeatherConfigSO selected = weatherRoster.weathers[index];
        CricketGameModel.Instance.SetSelectedWeather(selected);
        UpdateWeatherSummary(selected);
    }

    private void UpdateWeatherSummary(WeatherConfigSO weather)
    {
        if (weatherSummaryLabel == null) return;
        weatherSummaryLabel.text =
            CricketGameModel.Instance.GetDataController().GenerateWeatherSummary(weather);
    }

    private void OnApproachSelected(int index)
    {
        // Index 0 = Over the Wicket, Index 1 = Around the Wicket
        WicketApproach approach = index == 0 ? WicketApproach.Over : WicketApproach.Around;
        CricketGameModel.Instance.SetWicketApproach(approach);
    }

    private void OnBowlerSelected(int index)
    {
        if (roster == null || index < 0 || index >= roster.bowlers.Count) return;

        currentBowler = roster.bowlers[index];

        // SetSelectedBowler auto-sets bowlingArm for Left/Right bowlers
        CricketGameModel.Instance.SetSelectedBowler(currentBowler);

        RefreshPanelVisibility();
        RefreshSliderRanges();
    }

    private void OnSpeedChanged(float value)
    {
        CricketGameModel.Instance.SetDeliverySpeed(value);
        if (speedLabel != null)
            speedLabel.text = $"Speed: {value:F1} m/s  ({value * 3.6f:F0} km/h)";
    }

    private void OnSwingChanged(float value)
    {
        CricketGameModel.Instance.SetDeliverySwing(value);
        if (swingLabel != null)
        {
            string dir = value >  0.01f ? "In"
                       : value < -0.01f ? "Out"
                       : "Straight";
            swingLabel.text = $"Swing: {Mathf.Abs(value):F2} m/s\u00B2  ({dir})";
        }
    }

    private void OnSpinChanged(float value)
    {
        CricketGameModel.Instance.SetDeliverySpin(value);
        if (spinLabel != null)
        {
            string dir = value >  0.01f ? "Off"
                       : value < -0.01f ? "Leg"
                       : "Straight";
            spinLabel.text = $"Spin: {Mathf.Abs(value):F2} m/s  ({dir})";
        }
    }

    // ── Panel & arm refresh ───────────────────────────────────────────────────

    /// <summary>
    /// Shows swing controls for Fast and Medium; spin controls for Spin and Medium.
    /// </summary>
    private void RefreshPanelVisibility()
    {
        if (currentBowler == null) return;

        bool showSwing = currentBowler.bowlerType == BowlerType.Fast   ||
                         currentBowler.bowlerType == BowlerType.Medium;
        bool showSpin  = currentBowler.bowlerType == BowlerType.Spin   ||
                         currentBowler.bowlerType == BowlerType.Medium;

        if (swingGroup != null) swingGroup.SetActive(showSwing);
        if (spinGroup  != null) spinGroup.SetActive(showSpin);
    }

    /// <summary>
    /// Reconfigures slider min/max from the selected bowler's SO ranges.
    /// Setting slider.value fires the OnValueChanged callback which pushes
    /// the new value into CricketGameModel automatically.
    /// </summary>
    private void RefreshSliderRanges()
    {
        if (currentBowler == null) return;

        if (speedSlider != null)
        {
            speedSlider.minValue = currentBowler.minSpeed;
            speedSlider.maxValue = currentBowler.maxSpeed;
            speedSlider.value    = (currentBowler.minSpeed + currentBowler.maxSpeed) * 0.5f;
        }

        if (swingSlider != null)
        {
            // Signed range: negative = out-swing, positive = in-swing
            swingSlider.minValue = currentBowler.minSwingDirection * currentBowler.maxSwing;
            swingSlider.maxValue = currentBowler.maxSwingDirection * currentBowler.maxSwing;
            swingSlider.value    = 0f;
        }

        if (spinSlider != null)
        {
            // Signed range: negative = leg-break, positive = off-break
            spinSlider.minValue = currentBowler.minSpinDirection * currentBowler.maxSpin;
            spinSlider.maxValue = currentBowler.maxSpinDirection * currentBowler.maxSpin;
            spinSlider.value    = (spinSlider.minValue + spinSlider.maxValue) * 0.5f;
        }
    }
}
